/**
 * Cognitive Router - Type Definitions
 *
 * Shared types for the cognitive routing layer.
 */

import type { ModelId, Provider } from "./models";

// ==========================================
// Task Profiling
// ==========================================

/**
 * Task complexity levels
 */
export type TaskComplexity = "trivial" | "simple" | "moderate" | "complex";

/**
 * Risk tier for a task
 */
export type RiskTier = "auto" | "notify" | "review";

/**
 * Task profile generated by the profiler
 */
export interface TaskProfile {
  /** Unique task ID */
  taskId: string;

  /** Original input message */
  input: string;

  /** Detected complexity */
  complexity: TaskComplexity;

  /** Estimated input tokens */
  estimatedInputTokens: number;

  /** Estimated output tokens */
  estimatedOutputTokens: number;

  // Capability requirements
  requiresReasoning: boolean;
  requiresCode: boolean;
  requiresStructuredOutput: boolean;
  requiresCreativity: boolean;
  requiresLongContext: boolean;

  // Constraints
  latencySensitive: boolean;
  costSensitive: boolean;

  // Risk indicators
  touchesFilesystem: boolean;
  touchesAuth: boolean;
  executesCode: boolean;
  mutatesExternal: boolean;

  /** Detected tools needed */
  detectedTools: string[];

  /** Required context to load (progressive disclosure) */
  requiredContext: string[];
}

// ==========================================
// Model Selection
// ==========================================

/**
 * Model selection result from selector
 */
export interface ModelSelection {
  /** Selected model ID */
  modelId: ModelId;

  /** Why this model was selected */
  reasoning: string;

  /** Estimated cost for the request */
  estimatedCost: number;

  /** Fallback model if primary fails */
  fallbackModelId?: ModelId;
}

// ==========================================
// Provider Routing
// ==========================================

/**
 * Endpoint type for API routing
 */
export type Endpoint = "direct" | "openrouter" | "local";

/**
 * Provider routing result
 */
export interface ProviderRoute {
  /** Selected endpoint */
  endpoint: Endpoint;

  /** Provider to use */
  provider: Provider;

  /** Model ID (may differ for OpenRouter) */
  modelId: string;

  /** API key to use */
  apiKey: string | undefined;

  /** Base URL if different from default */
  baseUrl?: string;
}

// ==========================================
// Worker Execution
// ==========================================

/**
 * Worker request configuration
 */
export interface WorkerRequest {
  /** Task ID for tracking */
  taskId: string;

  /** Task profile */
  profile: TaskProfile;

  /** Selected model */
  model: ModelSelection;

  /** Provider route */
  route: ProviderRoute;

  /** System prompt */
  systemPrompt: string;

  /** User message */
  userMessage: string;

  /** Optional tools */
  tools?: WorkerTool[];

  /** Timeout in ms */
  timeoutMs?: number;

  /** Whether to require JSON output */
  jsonMode?: boolean;
}

/**
 * Tool definition for workers
 */
export interface WorkerTool {
  name: string;
  description: string;
  inputSchema: Record<string, unknown>;
}

/**
 * Worker execution result
 */
export interface WorkerResult {
  /** Task ID */
  taskId: string;

  /** Success status */
  success: boolean;

  /** Response content */
  content?: string;

  /** Parsed JSON if json mode */
  json?: unknown;

  /** Tool calls made */
  toolCalls?: WorkerToolCall[];

  /** Error if failed */
  error?: string;

  /** Token usage */
  usage: TokenUsage;

  /** Execution latency in ms */
  latencyMs: number;

  /** Model used */
  modelId: ModelId;

  /** Provider used */
  provider: Provider;

  /** Endpoint used */
  endpoint: Endpoint;
}

/**
 * Tool call result
 */
export interface WorkerToolCall {
  name: string;
  input: unknown;
  output: unknown;
}

/**
 * Token usage tracking
 */
export interface TokenUsage {
  inputTokens: number;
  outputTokens: number;
  totalTokens: number;
  cost: number;
}

// ==========================================
// Validation
// ==========================================

/**
 * Validation stage
 */
export type ValidationStage = "spec_compliance" | "output_quality";

/**
 * Validation result
 */
export interface ValidationResult {
  /** Stage that was validated */
  stage: ValidationStage;

  /** Whether validation passed */
  passed: boolean;

  /** Validation score (0-100) */
  score: number;

  /** Issues found */
  issues: string[];

  /** Suggestions for improvement */
  suggestions: string[];
}

// ==========================================
// Supervisor
// ==========================================

/**
 * Supervisor request for orchestration
 */
export interface SupervisorRequest {
  /** Original user input */
  input: string;

  /** Context from conversation */
  conversationHistory?: Array<{ role: "user" | "assistant"; content: string }>;

  /** Force specific model (override selection) */
  forceModel?: ModelId;

  /** Skip validation stages */
  skipValidation?: boolean;

  /** User ID for tracking */
  userId?: number;
}

/**
 * Supervisor response
 */
export interface SupervisorResponse {
  /** Success status */
  success: boolean;

  /** Response content */
  content: string;

  /** Whether human review is needed */
  needsReview: boolean;

  /** Review reason if needed */
  reviewReason?: string;

  /** Total cost of all workers */
  totalCost: number;

  /** Total latency */
  totalLatencyMs: number;

  /** All worker results */
  workerResults: WorkerResult[];

  /** Task ID for tracking */
  taskId: string;
}

// ==========================================
// Ledger & Persistence
// ==========================================

/**
 * Token ledger entry for Notion
 */
export interface TokenLedgerEntry {
  taskId: string;
  model: string;
  provider: Provider;
  endpoint: Endpoint;
  inputTokens: number;
  outputTokens: number;
  costUsd: number;
  latencyMs: number;
  success: boolean;
  timestamp: Date;
}

/**
 * Worker result entry for Notion
 */
export interface WorkerResultEntry {
  taskSummary: string;
  taskId: string;
  model: string;
  provider: Provider;
  endpoint: Endpoint;
  status: "Success" | "Failed" | "Timeout";
  costUsd: number;
  latencyMs: number;
  rerunnable: boolean;
  tokenSpendId?: string;
  created: Date;
}

// ==========================================
// Circuit Breaker
// ==========================================

/**
 * Circuit breaker state
 */
export interface CircuitBreakerState {
  /** Number of consecutive failures */
  failures: number;

  /** Last failure timestamp */
  lastFailure?: Date;

  /** Whether circuit is open (blocking requests) */
  isOpen: boolean;
}

/**
 * Circuit breaker response when max retries exceeded
 */
export interface CircuitBreakerResponse {
  status: "needs_human";
  message: string;
  attempts: WorkerResult[];
}
